micronaut:
  application:
    name: nslapi
  server:
    port: 8095
    host: localhost
  router:
    static-resources:
      main:
        paths: classpath:views
        mapping: /**
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/*
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /doc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /try/**

datasources:
  default:
    url: ${nslapi.db.url:`jdbc:postgresql://localhost:5432/nslapi`}
    username: ${nslapi.db.username:hasura}
    password: ${nslapi.db.password:hasura}
    driverClassName: org.postgresql.Driver
    autoCommit: false
    schema: ${nslapi.db.schema:api}
    socketTimeout: 30
---
nslapi:
  search:
    eLimit: ${nslapi.search.exactLimit:10}
    pLimit: ${nslapi.search.partialLimit:50}
