micronaut:
  application:
    name: nslapi
  server:
    port: 8095
    netty:
      worker:
        threads: 75
      parent:
        threads: 75
      childOptions:
        autoRead: true
  router:
    static-resources:
      main:
        paths: classpath:views
        mapping: /**
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/*
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /doc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /try/**
  http:
    client:
      max-content-length: 1010485760
      read-timeout: 300

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/api-test
    username: hasura
    password: hasura
    driverClassName: org.postgresql.Driver
    autoCommit: false
    schema: api
    socketTimeout: 30
---
nslapi:
  search:
    eLimit: ${nslapi.search.exactLimit:10}
    pLimit: ${nslapi.search.partialLimit:50}
  graphql:
    url: ${nslapi.graphql.url:`http://localhost:8080/v1/graphql/`}
    adminSecret: ${nslapi.graphql.adminSecret:admin}
