micronaut:
  application:
    name: nslapi
  server:
    port: 8095
    host: localhost
    netty:
      worker:
        threads: 75
      parent:
        threads: 75
      childOptions:
        autoRead: true
  http:
    client:
      max-content-length: 1010485760
  executors:
    io:
      type: fixed
      nThreads: 75
  router:
    static-resources:
      main:
        paths: classpath:views
        mapping: /**
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/*
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /doc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /try/**
endpoints:
  info:
    enabled: true
    sensitive: false

datasources:
  default:
    url: ${nslapi.db.url:`jdbc:postgresql://localhost:5432/nslapi`}
    username: ${nslapi.db.username:hasura}
    password: ${nslapi.db.password:hasura}
    driverClassName: org.postgresql.Driver
    autoCommit: false
    schema: ${nslapi.db.schema:api}
    socketTimeout: 30
---
nslapi:
  search:
    eLimit: ${nslapi.search.exactLimit:10}
    pLimit: ${nslapi.search.partialLimit:50}
  graphql:
    url: http://localhost:8080/v1/graphql/
    adminSecret: admin
  gnparser:
    apiUrl: https://parser.globalnames.org/api/v1/